Add PAPI functionality to Dr Hook
ecmwf-ifs/fiat pull request #26
Opened 2024-07-24 15:47 UTC by wdeconinck

This is cleaned up, updated and rebased PR superseding #18 

To enable the DR_HOOK hardware counters, use following environment variables for DR_HOOK-ed programs:
`DR_HOOK=1 DR_HOOK_OPT=COUNTERS`

The CMake feature DR_HOOK_PAPI is enabled by default when PAPI is found. This can be toggled with
 `-DENABLE_DR_HOOK_PAPI=ON|OFF`. In the case the feature is enabled, then the test `fiat_test_drhook_counters` is built. For unit-testing purpose, when run as part of `ctest`, the problem size is very small and the test runs in under 1 second.
 This test can also be run standalone:
```
<build-dir>/tests/fiat_test_drhook_counters
```
Then the problem size is by default what was chosen by @MartynF for sanity checks.
Upon finalisation the file drhook.prof.0.csv is created which contains all the counter information.

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF requested changes
Hi, Ioan asked me to have a look at this PR. I really like it overall, so I hope my harsh review doesn't make it seem like the contrary!

A lot of my comments are either for clarification or style : )

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook.c
> +    delta_counters=alloca(drhook_papi_num_counters() * sizeof(long_long) );
What is the reason for the use of `alloca`? I'd not come across it before and I'm wondering why it's chosen over `malloc_drhook` etc : )

Also, will it have an unintended affect on Dr Hook's memory tracking?

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook.c
> +	printf("DrHook: Note - no match for HOOK_OPT : %s\n",p);
Nice QoL improvement!

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +};
I appreciate this is probably not the intended long term solution for specifying counters, but is it worth making this more flexible now? My concern is that a temporary solution will become permanent.

Perhaps a `DR_HOOK_PAPI_COUNTERS` similar to how `DR_HOOK_OPT` is done? If not specified it could default to these 4. I am happy to implement this if we want to do this now : )

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +}
Should this be here? I'm of the opinion it's either:

1. Part of PAPI and should be namespaced as such
2. For general use and doesn't belong in this file

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +    long_long * tmp=alloca(drhook_papi_num_counters() * sizeof(long_long));
Similar comments about `alloca` as above

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +  long_long * tmp=alloca(drhook_papi_num_counters() * sizeof (long_long *));
Similar comments about `alloca` as above

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +  drhook_papi_event_set=malloc(nthreads*sizeof(int));
Should this be a `malloc_drhook`?

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +    printf("Fault: papi not running\n");
```suggestion
    printf("DRHOOK:PAPI: Error reading counters, papi is not running\n");
```

This and a few similar below are nitpicks, but I feel it's worth being consistent and explicit for extra clarity for users

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +    printf("Fault: Eventset was null\n");
```suggestion
    printf("HOOK:PAPI: Error reading counters, eventset was null\n");
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +    printf("DRHOOK:PAPI: Tried to initialise from a parallel region :-(\n");
```suggestion
    printf("DRHOOK:PAPI: Error, tried to initialise from a parallel region :-(\n");
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: library version mismatch between compilation and run!\n");
```suggestion
      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, library version mismatch between compilation and run!\n");
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: PAPI_EINVAL\n");
```suggestion
      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, PAPI_EINVAL\n");
```

This error is a bit cryptic to me, do we want to expand on what it means (**E**rror **IN**valid **VAL**ues given as arguments), or is this too much coupling?

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: PAPI_ENOMEM\n");
```suggestion
      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, PAPI_ENOMEM\n");
```

As above

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: PAPI_ESBSTR\n");
```suggestion
      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, PAPI_ESBSTR\n");
```
As above

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: PAPI_ESYS\n");
```suggestion
      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, PAPI_ESYS\n");
```
As above

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Unknown error code\n");
```suggestion
      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, unknown error code: %d\n", paperr);
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +    snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: thread init failed (%s)",PAPI_strerror(paperr));
```suggestion
    snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, thread init failed (%s)",PAPI_strerror(paperr));
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +    snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: create event set failed (%s) \n",PAPI_strerror(papiErr));
```suggestion
    snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, create event set failed (%s) \n",PAPI_strerror(papiErr));
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: event name to code failed (%s)",PAPI_strerror(papiErr));
```suggestion
      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, event name to code failed (%s)",PAPI_strerror(papiErr));
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: add_event failed: %d (%s)",papiErr,PAPI_strerror(papiErr));
```suggestion
      snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, add_event failed: %d (%s)",papiErr,PAPI_strerror(papiErr));
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/drhook_papi.c
> +    snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: starting counters failed (%d=%s)",papiErr,PAPI_strerror(papiErr));
```suggestion
    snprintf(pmsg,STD_MSG_LEN,"DRHOOK:PAPI: Error, starting counters failed (%d=%s)",papiErr,PAPI_strerror(papiErr));
```

2024-08-07 14:36 UTC, Andrew-Beggs-ECMWF commented on src/fiat/drhook/internal/drhook_run_omp_parallel.F90
> +  INTEGER(KIND=C_INT), VALUE :: n
```suggestion
  INTEGER(KIND=C_INT), VALUE, INTENT(IN) :: n
```

Should this have an `INTENT` attribute?

2024-08-26 08:28 UTC, wdeconinck commented
Hi @Andrew-Beggs-ECMWF discussing offline with @ioanhadade, @ioanhadade suggested for you to have a look at the possibility of integrating this within drhook itself.

2024-10-22 12:34 UTC, MartynF commented on src/fiat/drhook/drhook.c
> +    delta_counters=alloca(drhook_papi_num_counters() * sizeof(long_long) );
alloca is allocating on the stack, not on the heap - so fast, thread friendly, and with automatic deletion when the stack frame goes away. So this doesn't collide with Dr. Hooks heap allocator at all...

2024-10-22 12:37 UTC, MartynF commented on src/fiat/drhook/drhook_papi.c
> +    long_long * tmp=alloca(drhook_papi_num_counters() * sizeof(long_long));
Similar answer :-)

2024-10-22 12:38 UTC, MartynF commented on src/fiat/drhook/drhook_papi.c
> +  drhook_papi_event_set=malloc(nthreads*sizeof(int));
agree!

2024-10-22 12:39 UTC, MartynF commented on src/fiat/drhook/drhook_papi.c
> +    printf("Fault: papi not running\n");
agree!

2024-10-22 13:30 UTC, MartynF commented on src/fiat/drhook/internal/drhook_run_omp_parallel.F90
> +  INTEGER(KIND=C_INT), VALUE :: n
It could though VALUE is doing the heavy lifting already ...

2025-08-19 22:05 UTC, wdeconinck commented
This PR can be closed as #27 supersedes this, includes this, and further developed this. Thanks @MartynF !!!

2025-08-19 22:05 UTC, closed without merging