Merge fiat versions from CY49R1 and CY49T2 for CY50
ecmwf-ifs/fiat pull request #30
Opened 2024-11-13 14:25 UTC by AlexandreMary

This series of commits results from changes commited in fiat for CY49T2, merged with the version of fiat from CY49R1 (in the contrib/ directory of  `ifs-source`).

The final commit 6ddce647, tagged `for-CY50` in ACCORD-NWP fork of fiat, is the version bundled for CY50  at first (a version merged with a more recent version of fiat, could be later bundled).

2024-11-13 14:25 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/fiat?pullRequest=30) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/fiat?pullRequest=30) before we can accept your contribution.<br/>**1** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: pmarguinaud<br/>:x: meteoea<br/>:x: AlexandreMary<br/>:x: RyadElKhatibMF<br/>:x: ddegrauwe<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/fiat?pullRequest=30) it.</sub>

2025-01-29 13:39 UTC, wdeconinck commented
What is the meaning of `iswap` and `jswap`?

2025-01-29 14:08 UTC, wdeconinck requested changes
Hi @AlexandreMary thank you for this contribution to fiat.
The pull request is however made to the wrong branch (main). It should go to "develop" instead. Could you create a new PR for that?
Further, in the "develop" branch we already merged all the NVTX changes via https://github.com/ecmwf-ifs/fiat/pull/28/files, so that all NVTX-related changes can be omitted.

2025-01-29 14:08 UTC, wdeconinck commented on src/fiat/util/iswap8.c
What is the meaning of `iswap` and `jswap`?
I suggest to add some documentation in the code.
Also we can remove the '8' from the filename.

2025-01-29 14:08 UTC, wdeconinck commented on src/fiat/ellips/ellips.h
ellips routines have no place in fiat, but should remain in ectrans.
fiat should not deal with numerical algorithms, besides perhaps the qsort. Please omit these changes in the PR to develop.

2025-01-29 14:08 UTC, wdeconinck commented on src/mpi_serial/CMakeLists.txt
> +endif()
Was this a problem?
Normally this would be installed in "include/mpi_serial/mpi.h" and not be part of any regular include dir for downstream packages unless these packages link with mpi_serial cmake target.

2025-01-29 14:45 UTC, AlexandreMary commented on src/fiat/util/iswap8.c
@pmarguinaud can you answer to that ?

2025-01-29 14:51 UTC, AlexandreMary commented
> Hi @AlexandreMary thank you for this contribution to fiat. The pull request is however made to the wrong branch (main). It should go to "develop" instead. Could you create a new PR for that? Further, in the "develop" branch we already merged all the NVTX changes via https://github.com/ecmwf-ifs/fiat/pull/28/files, so that all NVTX-related changes can be omitted.

I changed the target to `develop`, is that enough ?
I agree it would be nicer to remove the commits, but this is a long-standing aggregate of additions from MF and ACCORD, and I'd rather not do archaeology to prune commits already merged.
Again, for upcoming contributions to fiat and other projects, we won't work with these long-standing forks but rather contribute more directly to fiat, but this is still from "the old world" when we had all in the same repo, basically.

2025-01-29 14:55 UTC, AlexandreMary commented on src/mpi_serial/CMakeLists.txt
> +endif()
@RyadElKhatibMF can you answer Willem ?

2025-01-29 14:57 UTC, pmarguinaud commented on src/fiat/util/iswap8.c
Hello,

iswap will swap your buffer (LE -> BE) if your system is little-endian, otherwise, just make a copy.
jswap will make a LE->BE transform.

I agree the names are not very well chosen.

2025-01-29 16:25 UTC, RyadElKhatibMF commented on src/mpi_serial/CMakeLists.txt
> +endif()
Hi Willem,
In our build system we can't filter what is installed below the directory include/ of a package. So that this mpi.h will be found and could be used by mistake.

2025-01-30 07:31 UTC, wdeconinck commented on src/mpi_serial/CMakeLists.txt
> +endif()
@RyadElKhatibMF  thank you for the explanation!

2025-01-30 13:14 UTC, wdeconinck commented on src/fiat/drhook/dr_hook_init.F90
> +    ENDIF
This change is not necessary. It is doing exactly the same as the statements just before, so that we can use 
`export DR_HOOK_ASSERT_MPI_INITIALIZED=0` (default 1) instead of `export DR_HOOK_NOT_MPI=1` (default 0)

2025-01-30 13:25 UTC, AlexandreMary commented on src/fiat/drhook/dr_hook_init.F90
> +    ENDIF
Indeed, but the question is rather why was this variable `DR_HOOK_ASSERT_MPI_INITIALIZED` introduced recently when `DR_HOOK_NOT_MPI` existed for a long time, and was already used for that purpose ?

2025-01-30 14:08 UTC, wdeconinck commented on src/fiat/drhook/dr_hook_init.F90
> +    ENDIF
DR_HOOK in fact does not initialise MPI anymore as it used to since July 2021 and should have been so in CY48R1 already.

The DR_HOOK_ASSERT_MPI_INITIALIZED (default ON) function is only there to catch use cases where programs were counting on DR_HOOK initialising MPI.

Either the program has a bug and aborts (case 1) and the program needs to first call MPL_INIT, or the program does not need MPI (case 2). This is the case where DR_HOOK_ASSERT_MPI_INITIALIZED=OFF should be used, or as in this PR also DR_HOOK_NOT_MPI=ON.

This function was only intended to be of temporary nature to be cautious with a hard abort for "case 1" until no more programs required fixing. I suppose this is the case by now, 3.5 years later, so that we can assume that "case 1" no longer exists.
A follow-up PR could just remove this function, or switch the default DR_HOOK_ASSERT_MPI_INITIALIZED=OFF, going forward after CY50. Then "case 2" is no longer a problem where we need to toggle this.

Apropos, I did a grep in ifs-source (CY48R1) and could only find two occurrences of DR_HOOK_NOT_MPI:
```
utilities/rdc/programs/master911.F90
105:CALL GET_ENVIRONMENT_VARIABLE('DR_HOOK_NOT_MPI',CLENV)

utilities/bcov_lam/programs/festat.F90
31:CALL GET_ENVIRONMENT_VARIABLE('DR_HOOK_NOT_MPI',CLENV)
```
In both cases it used to guard MPL_INIT, but *after* the first call to DR_HOOK. Very strange.

When introducing DR_HOOK_ASSERT_MPI_INITIALIZED it's safe to say I was not aware of DR_HOOK_NOT_MPI, only being present in these two tools that I doubt are used here.

2025-01-30 14:34 UTC, RyadElKhatibMF commented on src/fiat/drhook/dr_hook_init.F90
> +    ENDIF
Hi Willem,
I created DR_HOOK_NOT_MPI years ago, I don't remember exactly when but I can see it was already there in drhook.c or dr_hook_util.F90 of cycle 44. I believe it has been removed by the externalization of DrHook from ifsaux to fiat and the big re-write that was done around it at that time.
Never mind, I fully agree that programs should not count on DrHook to initialize MPI. For now we can agree to keep both DR_HOOK_NOT_MPI and DR_HOOK_ASSERT_MPI_INITIALIZED still for a while, or to remove both of them right now.

2025-01-30 15:40 UTC, wdeconinck commented on src/fiat/drhook/dr_hook_init.F90
> +    ENDIF
Hi @RyadElKhatibMF thank you for this info. That's very good to know. I will add this change back in #33 , and in the future it can be removed.

2025-01-31 07:32 UTC, wdeconinck commented
I have created a rebased PR #33 without conflicts and without NVTX and without ellips, which supersedes this PR.

2025-02-19 09:41 UTC, wdeconinck commented
#33 has been merged, so that we can close this PR.

2025-02-19 09:41 UTC, closed without merging